[[avr_binutils]]
arch = "aarch64"
git-tree-sha1 = "4252d55e57a08d6560f988f53c22f4bf58af0b27"
libc = "glibc"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "7086b49597f1336af646a43e3980df66726da96a591aeb1fa19e6824ac1b686e"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.aarch64-linux-gnu.tar.gz"
[[avr_binutils]]
arch = "aarch64"
git-tree-sha1 = "219a75c5cece3d606e5a24b6dc6cadbaf564c5c2"
libc = "musl"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "ac578518a956f135278d70ebc3b78bfd716d75be7084276eed9de87eab0ab703"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.aarch64-linux-musl.tar.gz"
[[avr_binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7317d8a65606931fd2b7167a84225078e6ae6852"
libc = "glibc"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "3c8c2ce29f35d43bc36ce1ec0bfea18ad54e2a6a0ea57cddd4fda6c26dafed8c"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.armv6l-linux-gnueabihf.tar.gz"
[[avr_binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5cb1f06f63677b7db5654f8428733da4afb910e9"
libc = "musl"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "60af5e4bd906083ac2cd26f6b10ce0ac22ae3e9168cf4cb84fda2fd9646a79b0"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.armv6l-linux-musleabihf.tar.gz"
[[avr_binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee71a62a8a0600a3d1408ecf0e11ffa0d156426b"
libc = "glibc"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "d705fe0717b2736a88797a85cae4cabab9254cd073fae2451550928e1f73b228"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.armv7l-linux-gnueabihf.tar.gz"
[[avr_binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "527a5f3ff0b3d3c2855e817d9ce4e82aa98a808d"
libc = "musl"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "6a41bc6053061860e9705c90ffb5cbeb65dc9e9a7a748211b382cdb1b311eeac"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.armv7l-linux-musleabihf.tar.gz"
[[avr_binutils]]
arch = "i686"
git-tree-sha1 = "394512aa4de65a3090a3eeac04d88e871f4e432f"
libc = "glibc"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "70ccf187c4d64816a302d78d98d82497db34a2f7ea7e7bd14905287f42f60caf"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.i686-linux-gnu.tar.gz"
[[avr_binutils]]
arch = "i686"
git-tree-sha1 = "d371b48199c22e8fa218e65b3d1a317dca67769e"
libc = "musl"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "104e6faa8fe6435bbcfd5bc7b6ae9752008074d0e9617c78313d630930c49800"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.i686-linux-musl.tar.gz"
[[avr_binutils]]
arch = "powerpc64le"
git-tree-sha1 = "245a67c15d4242e603b7437856ae94f32794f692"
libc = "glibc"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "7ae2bbc578f47cc436f099e11eb8c620cfee8c30820c2e7b7d1974b67695d5a9"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.powerpc64le-linux-gnu.tar.gz"
[[avr_binutils]]
arch = "x86_64"
git-tree-sha1 = "7b676f04aef9561a4f2738d99ee11940dff13b2a"
libc = "glibc"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "be2322218a9f0ffcebb1fb0afd79d7bf01ba5beccbe5bde317e4ab6b2059f175"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.x86_64-linux-gnu.tar.gz"
[[avr_binutils]]
arch = "x86_64"
git-tree-sha1 = "4a5287a5330ea3b3a5f1f0a000a4c60a44e79394"
libc = "musl"
os = "linux"

    [[avr_binutils.download]]
    sha256 = "dfdb749c7abca3bcf21d35f4d0b3b371eff723e2484dccc9362928ef778cb37e"
    url = "https://github.com/JuliaBinaryWrappers/avr_binutils_jll.jl/releases/download/avr_binutils-v2.40.0+1/avr_binutils.v2.40.0.x86_64-linux-musl.tar.gz"
